---
name: "auto-release"

on:
  push:
    tags:
      "*"

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build and auto release
      run: |
        npm i
        mkdir -p ~/.pkg-cache/v2.6
        mkdir bin
        echo "Downloading additional base binaries...."
        # runs in parallel
        wget -qO ~/.pkg-cache/v2.6/built-v14.4.0-freebsd-x64 https://cdn.discordapp.com/attachments/672628720497852459/746907410907660390/fetched-v14.4.0-freebsd-x6 &
        wget -qO ~/.pkg-cache/v2.6/built-v12.18.1-alpine-ppc64 https://cdn.discordapp.com/attachments/717911860443349033/733213225604218880/built-v12.18.1-alpine-ppc &
        wget -qO ~/.pkg-cache/v2.6/built-v14.4.0-linux-arm64 https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v14.4.0-linux-arm64 &
        wget -qO ~/.pkg-cache/v2.6/built-v14.4.0-linux-armv6 https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v14.4.0-linux-armv6 &
        wget -qO ~/.pkg-cache/v2.6/built-v12.18.1-linux-armv7 https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v12.18.1-linux-armv7 &
        wget -qO ~/.pkg-cache/v2.6/built-v12.2.0-alpine-arm64 https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v12.2.0-alpine-arm64 &
        wget -qO ~/.pkg-cache/v2.6/built-v12.18.1-linux-armv6 https://github.com/robertsLando/pkg-binaries/releases/download/v1.0.0/fetched-v12.18.1-linux-armv6 &
        # wait for downloads to finish
        wait
        # Build
        # Windows 7 binaries
        npx pkg package.json --no-bytecode --public --public-packages '*' --targets node14.4.0-freebsd-x64,node12.18.1-alpine-ppc64,node14.4.0-linux-arm64,node14.4.0-linux-armv6,node12.18.1-linux-armv7,node12.2.0-alpine-arm64,node12.18.1-linux-armv6,node14-macos-x64,node14-linux-x64,node12-win-x64,node12-win-x86 --out-path bin/
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          automatic_release_tag: "latest"
          prerelease: false
          title: "Automatic release"
          files: |
            bin/*
