---
name: "nightly"

on:
  push:
    branches: [ develop ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2
    - name: Build and auto release
      run: |
        sudo apt-get install osslsigncode -y
        npm i
        mkdir -p ~/.pkg-cache/v2.6
        mkdir bin
        echo "Downloading additional base binaries..."
        echo ${{secrets.PASSPHRASE}} > PASSPHRASE
        echo "${{secrets.PRIVATE_KEY}}" > key.pem
        npm run-script get-binaries
        npm run bsign
    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
          repo_token: "${{ secrets.GITHUBTOKEN }}"
          automatic_release_tag: "nightly"
          prerelease: true
          files: |
            bin/*
